//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGeneration.Soap.Maint {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EndpointValidationError", Namespace="http://www.acumatica.com/entity/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DataGeneration.Soap.Maint.EntityNameNotUniqueValidationError))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DataGeneration.Soap.Maint.EntityNotExistsValidationError))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DataGeneration.Soap.Maint.InvalidMappingActionValidationError))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DataGeneration.Soap.Maint.InvalidNameActionValidationError))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DataGeneration.Soap.Maint.InvalidMappingEntityValidationError))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DataGeneration.Soap.Maint.InvalidNameEntityValidationError))]
    public partial class EndpointValidationError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TopLevelEntityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldFullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TopLevelEntity {
            get {
                return this.TopLevelEntityField;
            }
            set {
                if ((object.ReferenceEquals(this.TopLevelEntityField, value) != true)) {
                    this.TopLevelEntityField = value;
                    this.RaisePropertyChanged("TopLevelEntity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FieldFullName {
            get {
                return this.FieldFullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldFullNameField, value) != true)) {
                    this.FieldFullNameField = value;
                    this.RaisePropertyChanged("FieldFullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityNameNotUniqueValidationError", Namespace="http://www.acumatica.com/entity/")]
    [System.SerializableAttribute()]
    public partial class EntityNameNotUniqueValidationError : DataGeneration.Soap.Maint.EndpointValidationError {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityNotExistsValidationError", Namespace="http://www.acumatica.com/entity/")]
    [System.SerializableAttribute()]
    public partial class EntityNotExistsValidationError : DataGeneration.Soap.Maint.EndpointValidationError {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidMappingActionValidationError", Namespace="http://www.acumatica.com/entity/")]
    [System.SerializableAttribute()]
    public partial class InvalidMappingActionValidationError : DataGeneration.Soap.Maint.EndpointValidationError {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidNameActionValidationError", Namespace="http://www.acumatica.com/entity/")]
    [System.SerializableAttribute()]
    public partial class InvalidNameActionValidationError : DataGeneration.Soap.Maint.EndpointValidationError {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidMappingEntityValidationError", Namespace="http://www.acumatica.com/entity/")]
    [System.SerializableAttribute()]
    public partial class InvalidMappingEntityValidationError : DataGeneration.Soap.Maint.EndpointValidationError {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidNameEntityValidationError", Namespace="http://www.acumatica.com/entity/")]
    [System.SerializableAttribute()]
    public partial class InvalidNameEntityValidationError : DataGeneration.Soap.Maint.EndpointValidationError {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.acumatica.com/entity/", ConfigurationName="Soap.Maint.EntityMaintenanceSoap")]
    public interface EntityMaintenanceSoap {
        
        // CODEGEN: Generating message contract since element name version from namespace http://www.acumatica.com/entity/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/entity/ValidateEndpoint", ReplyAction="*")]
        DataGeneration.Soap.Maint.ValidateEndpointResponse ValidateEndpoint(DataGeneration.Soap.Maint.ValidateEndpointRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/entity/ValidateEndpoint", ReplyAction="*")]
        System.Threading.Tasks.Task<DataGeneration.Soap.Maint.ValidateEndpointResponse> ValidateEndpointAsync(DataGeneration.Soap.Maint.ValidateEndpointRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://www.acumatica.com/entity/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/entity/Login", ReplyAction="*")]
        DataGeneration.Soap.Maint.LoginResponse Login(DataGeneration.Soap.Maint.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/entity/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<DataGeneration.Soap.Maint.LoginResponse> LoginAsync(DataGeneration.Soap.Maint.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/entity/Logout", ReplyAction="*")]
        void Logout();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/entity/Logout", ReplyAction="*")]
        System.Threading.Tasks.Task LogoutAsync();
        
        // CODEGEN: Generating message contract since element name version from namespace http://www.acumatica.com/entity/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/entity/GetSchema", ReplyAction="*")]
        DataGeneration.Soap.Maint.GetSchemaResponse GetSchema(DataGeneration.Soap.Maint.GetSchemaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/entity/GetSchema", ReplyAction="*")]
        System.Threading.Tasks.Task<DataGeneration.Soap.Maint.GetSchemaResponse> GetSchemaAsync(DataGeneration.Soap.Maint.GetSchemaRequest request);
        
        // CODEGEN: Generating message contract since element name schema from namespace http://www.acumatica.com/entity/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/entity/PutSchema", ReplyAction="*")]
        DataGeneration.Soap.Maint.PutSchemaResponse PutSchema(DataGeneration.Soap.Maint.PutSchemaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/entity/PutSchema", ReplyAction="*")]
        System.Threading.Tasks.Task<DataGeneration.Soap.Maint.PutSchemaResponse> PutSchemaAsync(DataGeneration.Soap.Maint.PutSchemaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/entity/GetCurrentSystemContractVersion", ReplyAction="*")]
        int GetCurrentSystemContractVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/entity/GetCurrentSystemContractVersion", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetCurrentSystemContractVersionAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateEndpointRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateEndpoint", Namespace="http://www.acumatica.com/entity/", Order=0)]
        public DataGeneration.Soap.Maint.ValidateEndpointRequestBody Body;
        
        public ValidateEndpointRequest() {
        }
        
        public ValidateEndpointRequest(DataGeneration.Soap.Maint.ValidateEndpointRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.acumatica.com/entity/")]
    public partial class ValidateEndpointRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string version;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string endpoint;
        
        public ValidateEndpointRequestBody() {
        }
        
        public ValidateEndpointRequestBody(string version, string endpoint) {
            this.version = version;
            this.endpoint = endpoint;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateEndpointResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateEndpointResponse", Namespace="http://www.acumatica.com/entity/", Order=0)]
        public DataGeneration.Soap.Maint.ValidateEndpointResponseBody Body;
        
        public ValidateEndpointResponse() {
        }
        
        public ValidateEndpointResponse(DataGeneration.Soap.Maint.ValidateEndpointResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.acumatica.com/entity/")]
    public partial class ValidateEndpointResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DataGeneration.Soap.Maint.EndpointValidationError[] ValidateEndpointResult;
        
        public ValidateEndpointResponseBody() {
        }
        
        public ValidateEndpointResponseBody(DataGeneration.Soap.Maint.EndpointValidationError[] ValidateEndpointResult) {
            this.ValidateEndpointResult = ValidateEndpointResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://www.acumatica.com/entity/", Order=0)]
        public DataGeneration.Soap.Maint.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(DataGeneration.Soap.Maint.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.acumatica.com/entity/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string company;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string branch;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string locale;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string name, string password, string company, string branch, string locale) {
            this.name = name;
            this.password = password;
            this.company = company;
            this.branch = branch;
            this.locale = locale;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://www.acumatica.com/entity/", Order=0)]
        public DataGeneration.Soap.Maint.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(DataGeneration.Soap.Maint.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LoginResponseBody {
        
        public LoginResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSchemaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSchema", Namespace="http://www.acumatica.com/entity/", Order=0)]
        public DataGeneration.Soap.Maint.GetSchemaRequestBody Body;
        
        public GetSchemaRequest() {
        }
        
        public GetSchemaRequest(DataGeneration.Soap.Maint.GetSchemaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.acumatica.com/entity/")]
    public partial class GetSchemaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string version;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string endpoint;
        
        public GetSchemaRequestBody() {
        }
        
        public GetSchemaRequestBody(string version, string endpoint) {
            this.version = version;
            this.endpoint = endpoint;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSchemaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSchemaResponse", Namespace="http://www.acumatica.com/entity/", Order=0)]
        public DataGeneration.Soap.Maint.GetSchemaResponseBody Body;
        
        public GetSchemaResponse() {
        }
        
        public GetSchemaResponse(DataGeneration.Soap.Maint.GetSchemaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.acumatica.com/entity/")]
    public partial class GetSchemaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSchemaResult;
        
        public GetSchemaResponseBody() {
        }
        
        public GetSchemaResponseBody(string GetSchemaResult) {
            this.GetSchemaResult = GetSchemaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutSchemaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutSchema", Namespace="http://www.acumatica.com/entity/", Order=0)]
        public DataGeneration.Soap.Maint.PutSchemaRequestBody Body;
        
        public PutSchemaRequest() {
        }
        
        public PutSchemaRequest(DataGeneration.Soap.Maint.PutSchemaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.acumatica.com/entity/")]
    public partial class PutSchemaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string schema;
        
        public PutSchemaRequestBody() {
        }
        
        public PutSchemaRequestBody(string schema) {
            this.schema = schema;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutSchemaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutSchemaResponse", Namespace="http://www.acumatica.com/entity/", Order=0)]
        public DataGeneration.Soap.Maint.PutSchemaResponseBody Body;
        
        public PutSchemaResponse() {
        }
        
        public PutSchemaResponse(DataGeneration.Soap.Maint.PutSchemaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PutSchemaResponseBody {
        
        public PutSchemaResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EntityMaintenanceSoapChannel : DataGeneration.Soap.Maint.EntityMaintenanceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EntityMaintenanceSoapClient : System.ServiceModel.ClientBase<DataGeneration.Soap.Maint.EntityMaintenanceSoap>, DataGeneration.Soap.Maint.EntityMaintenanceSoap {
        
        public EntityMaintenanceSoapClient() {
        }
        
        public EntityMaintenanceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EntityMaintenanceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntityMaintenanceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntityMaintenanceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataGeneration.Soap.Maint.ValidateEndpointResponse DataGeneration.Soap.Maint.EntityMaintenanceSoap.ValidateEndpoint(DataGeneration.Soap.Maint.ValidateEndpointRequest request) {
            return base.Channel.ValidateEndpoint(request);
        }
        
        public DataGeneration.Soap.Maint.EndpointValidationError[] ValidateEndpoint(string version, string endpoint) {
            DataGeneration.Soap.Maint.ValidateEndpointRequest inValue = new DataGeneration.Soap.Maint.ValidateEndpointRequest();
            inValue.Body = new DataGeneration.Soap.Maint.ValidateEndpointRequestBody();
            inValue.Body.version = version;
            inValue.Body.endpoint = endpoint;
            DataGeneration.Soap.Maint.ValidateEndpointResponse retVal = ((DataGeneration.Soap.Maint.EntityMaintenanceSoap)(this)).ValidateEndpoint(inValue);
            return retVal.Body.ValidateEndpointResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataGeneration.Soap.Maint.ValidateEndpointResponse> DataGeneration.Soap.Maint.EntityMaintenanceSoap.ValidateEndpointAsync(DataGeneration.Soap.Maint.ValidateEndpointRequest request) {
            return base.Channel.ValidateEndpointAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataGeneration.Soap.Maint.ValidateEndpointResponse> ValidateEndpointAsync(string version, string endpoint) {
            DataGeneration.Soap.Maint.ValidateEndpointRequest inValue = new DataGeneration.Soap.Maint.ValidateEndpointRequest();
            inValue.Body = new DataGeneration.Soap.Maint.ValidateEndpointRequestBody();
            inValue.Body.version = version;
            inValue.Body.endpoint = endpoint;
            return ((DataGeneration.Soap.Maint.EntityMaintenanceSoap)(this)).ValidateEndpointAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataGeneration.Soap.Maint.LoginResponse DataGeneration.Soap.Maint.EntityMaintenanceSoap.Login(DataGeneration.Soap.Maint.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public void Login(string name, string password, string company, string branch, string locale) {
            DataGeneration.Soap.Maint.LoginRequest inValue = new DataGeneration.Soap.Maint.LoginRequest();
            inValue.Body = new DataGeneration.Soap.Maint.LoginRequestBody();
            inValue.Body.name = name;
            inValue.Body.password = password;
            inValue.Body.company = company;
            inValue.Body.branch = branch;
            inValue.Body.locale = locale;
            DataGeneration.Soap.Maint.LoginResponse retVal = ((DataGeneration.Soap.Maint.EntityMaintenanceSoap)(this)).Login(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataGeneration.Soap.Maint.LoginResponse> DataGeneration.Soap.Maint.EntityMaintenanceSoap.LoginAsync(DataGeneration.Soap.Maint.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataGeneration.Soap.Maint.LoginResponse> LoginAsync(string name, string password, string company, string branch, string locale) {
            DataGeneration.Soap.Maint.LoginRequest inValue = new DataGeneration.Soap.Maint.LoginRequest();
            inValue.Body = new DataGeneration.Soap.Maint.LoginRequestBody();
            inValue.Body.name = name;
            inValue.Body.password = password;
            inValue.Body.company = company;
            inValue.Body.branch = branch;
            inValue.Body.locale = locale;
            return ((DataGeneration.Soap.Maint.EntityMaintenanceSoap)(this)).LoginAsync(inValue);
        }
        
        public void Logout() {
            base.Channel.Logout();
        }
        
        public System.Threading.Tasks.Task LogoutAsync() {
            return base.Channel.LogoutAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataGeneration.Soap.Maint.GetSchemaResponse DataGeneration.Soap.Maint.EntityMaintenanceSoap.GetSchema(DataGeneration.Soap.Maint.GetSchemaRequest request) {
            return base.Channel.GetSchema(request);
        }
        
        public string GetSchema(string version, string endpoint) {
            DataGeneration.Soap.Maint.GetSchemaRequest inValue = new DataGeneration.Soap.Maint.GetSchemaRequest();
            inValue.Body = new DataGeneration.Soap.Maint.GetSchemaRequestBody();
            inValue.Body.version = version;
            inValue.Body.endpoint = endpoint;
            DataGeneration.Soap.Maint.GetSchemaResponse retVal = ((DataGeneration.Soap.Maint.EntityMaintenanceSoap)(this)).GetSchema(inValue);
            return retVal.Body.GetSchemaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataGeneration.Soap.Maint.GetSchemaResponse> DataGeneration.Soap.Maint.EntityMaintenanceSoap.GetSchemaAsync(DataGeneration.Soap.Maint.GetSchemaRequest request) {
            return base.Channel.GetSchemaAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataGeneration.Soap.Maint.GetSchemaResponse> GetSchemaAsync(string version, string endpoint) {
            DataGeneration.Soap.Maint.GetSchemaRequest inValue = new DataGeneration.Soap.Maint.GetSchemaRequest();
            inValue.Body = new DataGeneration.Soap.Maint.GetSchemaRequestBody();
            inValue.Body.version = version;
            inValue.Body.endpoint = endpoint;
            return ((DataGeneration.Soap.Maint.EntityMaintenanceSoap)(this)).GetSchemaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataGeneration.Soap.Maint.PutSchemaResponse DataGeneration.Soap.Maint.EntityMaintenanceSoap.PutSchema(DataGeneration.Soap.Maint.PutSchemaRequest request) {
            return base.Channel.PutSchema(request);
        }
        
        public void PutSchema(string schema) {
            DataGeneration.Soap.Maint.PutSchemaRequest inValue = new DataGeneration.Soap.Maint.PutSchemaRequest();
            inValue.Body = new DataGeneration.Soap.Maint.PutSchemaRequestBody();
            inValue.Body.schema = schema;
            DataGeneration.Soap.Maint.PutSchemaResponse retVal = ((DataGeneration.Soap.Maint.EntityMaintenanceSoap)(this)).PutSchema(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataGeneration.Soap.Maint.PutSchemaResponse> DataGeneration.Soap.Maint.EntityMaintenanceSoap.PutSchemaAsync(DataGeneration.Soap.Maint.PutSchemaRequest request) {
            return base.Channel.PutSchemaAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataGeneration.Soap.Maint.PutSchemaResponse> PutSchemaAsync(string schema) {
            DataGeneration.Soap.Maint.PutSchemaRequest inValue = new DataGeneration.Soap.Maint.PutSchemaRequest();
            inValue.Body = new DataGeneration.Soap.Maint.PutSchemaRequestBody();
            inValue.Body.schema = schema;
            return ((DataGeneration.Soap.Maint.EntityMaintenanceSoap)(this)).PutSchemaAsync(inValue);
        }
        
        public int GetCurrentSystemContractVersion() {
            return base.Channel.GetCurrentSystemContractVersion();
        }
        
        public System.Threading.Tasks.Task<int> GetCurrentSystemContractVersionAsync() {
            return base.Channel.GetCurrentSystemContractVersionAsync();
        }
    }
}
